version: '3.8'

services:
  api:
    build: .
    volumes:
      - .:/app:cached
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
    ports:
      - 8008:8000
    depends_on:
      - db
    env_file:
      - ./.env
    environment: &api-environment
      SECRET_KEY: secret_key
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_SERVER: db
      POSTGRES_PORT: 5432

    command: uvicorn main:app --reload --host 0.0.0.0

  db:
    image: postgres:12.5
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
